# Minimal Edit Distance 

In [1]:
from numpy import *

In [76]:
def min_edit_distance(source_word, target_word):  
    len_source_word = len(source_word)+ 1
    len_target_word = len(target_word)+ 1
    the_matrix = zeros ((len_source_word, len_target_word))
    
    for x in range(len_source_word):
        the_matrix [x, 0] = x
        
    for y in range(len_target_word):
        the_matrix [0, y] = y
        
#This is 
    for x in range(1, len_source_word):
        for y in range(1, len_target_word):
            #print(source_word[x-1], target_word[y-1])
            if source_word[x-1] == target_word[y-1]:
                the_matrix [x,y] = min(
                    the_matrix[x-1, y] + 1,
                    the_matrix[x, y-1] + 1,
                    the_matrix[x-1, y-1]+ 0)
            else:
               # print(source_word[x-1], target_word[y-1])
                the_matrix [x,y] = min(
                    the_matrix[x-1,y] + 1,
                    the_matrix[x,y-1] + 1,
                    the_matrix[x-1,y-1] + 2)
            
            
                
    print("The Matrix Results")            
    print (the_matrix)
    print ("The minimal edit distance between "+source_word+" and the "+target_word+" is " + str(int(the_matrix[len_source_word - 1, len_target_word - 1]))+".")

In [77]:
min_edit_distance("execution", "intention")

min_edit_distance("tell", "feel")

The Matrix Results
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  3.  4.  5.  6.  7.  8.]
 [ 2.  3.  4.  5.  4.  5.  6.  7.  8.  9.]
 [ 3.  4.  5.  6.  5.  6.  7.  8.  9. 10.]
 [ 4.  5.  6.  7.  6.  7.  8.  9. 10. 11.]
 [ 5.  6.  7.  8.  7.  8.  9. 10. 11. 12.]
 [ 6.  7.  8.  7.  8.  9.  8.  9. 10. 11.]
 [ 7.  6.  7.  8.  9. 10.  9.  8.  9. 10.]
 [ 8.  7.  8.  9. 10. 11. 10.  9.  8.  9.]
 [ 9.  8.  7.  8.  9. 10. 11. 10.  9.  8.]]
The minimal edit distance between execution and the intention is 8.
The Matrix Results
[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 2. 3. 4.]
 [3. 4. 3. 4. 3.]
 [4. 5. 4. 5. 4.]]
The minimal edit distance between tell and the feel is 4.
